# Generated by Django 3.0.4 on 2020-10-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('features', models.TextField(max_length=200)),
                ('mainPicBig', models.CharField(max_length=100)),
                ('mainPicSmall', models.CharField(max_length=100)),
                ('detailPicBig', models.CharField(max_length=100)),
                ('detailPicSmall', models.CharField(max_length=100)),
            ],
        ),
    ]
